defaults: &defaults
  solr_host: solr.yourdomain.org
  solr_port: '8983'
  solr_core_path: /solr/collection_guides/
  solr_core_name: collection_guides
  archivesspace_host: archivesspace.yourdomain.org
  archivesspace_backend_port: '8089'
  archivesspace_frontend_port: '8080'
  archivesspace_solr_port: '8090'
  archivesspace_solr_path: '/collection1/'
  archivesspace_username: admin_username
  archivesspace_password: admin_password

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
