-
  label: 'Khayrallah Center'
  url: 'https://lebanesestudies.ncsu.edu/'
  target: '_khayrallah'
-
  label: 'Contact'
  url: 'http://www.lib.ncsu.edu/scrc/request'
-
  label: 'Get help'
  url: '/findingaids/help'
